spring:
  application:
    name: oKDo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/okdo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  mail:
    host: smtp.qq.com
    port: 465
    username: 461420681@qq.com
    password: fxzcsizxryosbjef
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

