spring:
  application:
    name: oKDo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/okdo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  mail:
    host: smtp.qq.com
    port: 465
    username: okDo_timer@qq.com
    protocol: smtps
    password: ogsbqinyysogcfje
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  redis:
    host: localhost
    database: 0
    port: 6379

jwt:
    secret: tuasky-vdjosdcofjifeomkpeopm
    expiration: 864000000



